bettorgame/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('maingame.urls', namespace="maingame")),
    path('', include('maingame.urls', namespace="maingame")),
    path('accounts/', include('django.contrib.auth.urls'))
]

maingame/urls.py
from django.urls import path

from . import views

app_name = 'maingame'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('join-group-and-event', views.join_group_and_event, name='join_group_and_event'),
    path('create-group-and-event', views.create_group_and_event, name='create_group_and_event'),
    path('<int:group_id>/<int:event_id>/play', views.play, name='play'),
    path('<int:group_id>/<int:event_id>/group-admin', views.group_admin, name='group_admin'),
    path('<int:group_id>/<int:event_id>/set-stakes', views.set_stakes, name='set_stakes'),
    path('<int:group_id>/<int:event_id>/add-bets', views.add_bets, name='add_bets'),
    path('<int:group_id>/<int:event_id>/create-bet', views.create_bet, name='create_bet'),
    path('<int:group_id>/<int:event_id>/start-event', views.start_event, name='start_event'),
    path('<int:group_id>/<int:event_id>/end-event', views.end_event, name='end_event'),
    path('<int:group_id>/<int:event_id>/lock-bets', views.lock_bets, name='lock_bets'),
    path('<int:group_id>/<int:event_id>/show-placements', views.show_placements, name='show_placements'),
    path('<int:group_id>/<int:event_id>/create-placements', views.create_placements, name='create_placements'),
    path('<int:group_id>/<int:event_id>/running-bets', views.running_bets, name='running_bets'),
    path('<int:group_id>/<int:event_id>/admin_bet_result', views.admin_bet_result, name='admin_bet_result'),
    path('<int:group_id>/<int:event_id>/leaderboard', views.leaderboard, name='leaderboard'),
]

bettorgame/maingame/models.py
from django.db import models
from .utils import db_defaults

class EventType(models.Model):
    name = models.TextField()

class StatusType(models.Model):
    name = models.TextField()

class UserRole(models.Model):
    name = models.TextField()

class User(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(
        max_length=200,
        blank=True
    )
    join_date = models.DateTimeField()
    email = models.CharField(max_length=200)
    phone_number = models.IntegerField(
        null=True,
        blank=True
    )

class Group(models.Model):
    players = models.ManyToManyField(User)
    name = models.CharField(max_length=200)

class Event(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    type = models.ForeignKey(
        EventType,
        null=True,
        on_delete=models.SET_NULL
    )
    players = models.ManyToManyField(User)
    groups = models.ManyToManyField(Group)
    name = models.CharField(max_length=200)
    stakes = models.TextField()

class UserGroupRole(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE
    )
    role = models.ForeignKey(
        UserRole,
        default=db_defaults.set_default_role,
        on_delete=models.SET_DEFAULT
    )

class UserEventRole(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE
    )
    role = models.ForeignKey(
        UserRole,
        default=db_defaults.set_default_role,
        on_delete=models.SET_DEFAULT
    )

class Bet(models.Model):
    creator = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING
    )
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE
    )
    created_time = models.DateTimeField()
    start_time = models.DateTimeField()
    question = models.TextField()
    notes = models.TextField(blank=True)
    multiplier = models.FloatField(default=1)
    status = models.ForeignKey(
        StatusType,
        null=True,
        on_delete=models.SET_NULL
    )

    outcome = models.TextField(blank=True)
    end_time = models.DateTimeField(null=True)

class BetOption(models.Model):
    bet = models.ForeignKey(
        Bet,
        on_delete=models.CASCADE
    )
    text = models.CharField(max_length=200)

class Placement(models.Model):
    player = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING
    )
    bet = models.ForeignKey(
        Bet,
        on_delete=models.CASCADE
    )
    option = models.ForeignKey(
        BetOption,
        null=True,
        on_delete=models.SET_NULL
    )
    custom_option = models.CharField(
        max_length=200,
        blank=True
    )

class BetResult(models.Model):
    player = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    bet = models.ForeignKey(
        Bet,
        on_delete=models.CASCADE
    )
    score = models.FloatField()

class EventResult(models.Model):
    player = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE
    )
    score = models.FloatField()
    rank = models.IntegerField()

maingame/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(required=True, label="First Name")
    email = forms.EmailField(required=True, label="Email")

    class Meta:
        model = User
        fields = ("first_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.username = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        if commit:
            user.save()
        return user

bettorgame/maingame/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import User, Group, Event, UserGroupRole, UserEventRole, Bet, BetOption, Placement, EventResult, BetResult, EventType, StatusType, UserRole
from django.contrib import messages
import datetime
import pytz
import pdb

#How to render this check to see if user is ADMIN on basetemplate / other pages?
#UserEventRole.objects.get(user=request.user.id, event=event_id))
#can this be done more intelligently with middleware?

def login(request):

    return render(request, 'login.html', {})

def login_user(request):
    #Lisa will be updating authetntication
    try:
      email = request.POST["loginEmail"]
      existing_user = User.objects.get(
        email=email
        )
      if existing_user:
        request.session['is_authenticated'] = True

        return HttpResponseRedirect(reverse('index'))

    except (KeyError, User.DoesNotExist):
      # Redisplay the login form.
      return render(
        request, 
        'login.html', 
        {
        'error_message_login': "Hmm, we don't have that email registered. Maybe there was a typo or sign up under 'New User' below!"
        })
    

def create_user(request):
    email = request.POST["createEmail"]
    existing_user = User.objects.filter(
      email=email
      )
    
    if existing_user:
      return render(
        request, 
        'login.html', 
        {
        'error_message_create': "This email is already registered. Please login above!"
        })
    
    else:
      first_name = request.POST["createFirstName"]
      join_date = datetime.datetime.now().replace(tzinfo=pytz.UTC)

      User.objects.create(
        first_name=first_name, 
        join_date=join_date, 
        email=email
        )

      return HttpResponseRedirect(reverse('index'))

def index(request):

  return render(request, 'index.html', {})

def join_group_and_event(request):
    try:
      groupAndEventIdArray = request.POST["groupAndEventId"].split('-')
      group = Group.objects.get(
        id=groupAndEventIdArray[0]
        )
      event = Event.objects.get(
        id=groupAndEventIdArray[1]
        )

      return HttpResponseRedirect(reverse('add_bets', args=[group.id, event.id]))

    except:
        # Redisplay the question voting form.
        return render(
          request, 
          'index.html', 
          {
          'error_message': "There is no Group with that code."
          })

def create_group_and_event(request):
    new_group = Group.objects.create(
      name=request.POST["groupName"]
      )

    placeholder_future_start_date = datetime.datetime.now().replace(tzinfo=pytz.UTC) + datetime.timedelta(days=365)
    placeholder_future_end_date = placeholder_future_start_date + datetime.timedelta(days=7)
    placeholder_stakes = 'TBD'

    new_event = Event.objects.create(
      start_time=placeholder_future_start_date, 
      end_time=placeholder_future_end_date, 
      name=new_group.name, 
      stakes=placeholder_stakes
      )

    user = User.objects.get(
      id=request.user.id
      )

    new_group.players.add(user)
    new_event.players.add(user)
    new_event.groups.add(new_group)

    role_admin = UserRole.objects.get(id=1)

    UserGroupRole.objects.create(
      user=user, 
      group=new_group, 
      role=role_admin
      )
    
    UserEventRole.objects.create(
      user=user, 
      event=new_event, 
      role=role_admin
      )

    return HttpResponseRedirect(reverse('group_admin', args=[new_group.id, new_event.id]))

def group_admin(request, group_id, event_id):
    event = Event.objects.get(
      id=event_id
      )
    group = Group.objects.get(
      id=group_id
      )

    is_event_started = event.start_time < datetime.datetime.now().replace(tzinfo=pytz.UTC)
    is_event_ended = event.end_time < datetime.datetime.now().replace(tzinfo=pytz.UTC)
    event_status = {
    'is_event_started': is_event_started, 
    'is_event_ended': is_event_ended
    }

    return render(
      request, 
      'group-admin.html', 
      {
      'event': event, 
      'group': group, 
      'event_status': event_status
      })

def set_stakes(request, group_id, event_id):
    event = Event.objects.get(
      id=event_id
      )
    event.stakes = request.POST["setStakes"]

    return HttpResponseRedirect(reverse('add_bets', args=(group_id,event_id,)))

def start_event(request, group_id, event_id):
    event = Event.objects.get(
      id=event_id
      )
    event.start_time = datetime.datetime.now()

    return HttpResponseRedirect(reverse('group_admin', args=(group_id,event_id,)))

def end_event(request, group_id, event_id):
    event = Event.objects.get(
      id=event_id
      )

    event.end_time = datetime.datetime.now().replace(tzinfo=pytz.UTC)

    return HttpResponseRedirect(reverse('group_admin', args=(group_id,event_id,)))

def add_bets(request, group_id, event_id):
    event = Event.objects.get(
      id=event_id
      )

    event_commissioner = UserEventRole.objects.get(
      role=1, event=event_id
      ).user.first_name

    player_first_names = [player.first_name for player in event.players.all()]

    #should this be moved to a method somewhere outside of this file so I can reuse?
    try:
      bets_list = [
      {
      'bet': bet, 
      'bet_options': BetOption.objects.filter(bet=bet).order_by('id')
      } 
      for bet in Bet.objects.filter(event=event_id)
      ]



    except:
      bets_list = None

    return render(
      request, 
      'add-bets.html', 
      {
      'event': event, 
      'group_id': group_id, 
      'player_first_names': player_first_names, 
      'event_commissioner': event_commissioner, 
      'bets_list': bets_list
      })

def create_bet(request, group_id, event_id):
    event = Event.objects.get(
      id=event_id
      )
    creator = User.objects.get(
      id=request.user.id
      )

    new_bet = Bet.objects.create(
      creator=creator, 
      event=event, 
      created_time=datetime.datetime.now().replace(tzinfo=pytz.UTC), 
      start_time=datetime.datetime.now().replace(tzinfo=pytz.UTC), 
      end_time=datetime.datetime.now().replace(tzinfo=pytz.UTC), 
      question=request.POST['betQuestion'], 
      status=StatusType.objects.get(id=1)
      )

    BetOption.objects.create(
      bet=new_bet, 
      text=request.POST['betOption1']
      )

    BetOption.objects.create(
      bet=new_bet, 
      text=request.POST['betOption2']
      )

    return HttpResponseRedirect(reverse('add_bets', args=(group_id,event_id,)))

def show_placements(request, group_id, event_id):
    event = Event.objects.get(
      id=event_id
      )

    event_commissioner = UserEventRole.objects.get(
      role=1, event=event_id
      ).user

    # Same comment as in add_bets
    # Still need to update to nested list comprehenseion
    try:
      bets_list = []
      bets = Bet.objects.filter(
        event=event_id
        )
      for bet in bets:
        bet_options = BetOption.objects.filter(
          bet=bet
          ).order_by('id')
        bet_options_and_names = []
        for bet_option in bet_options:
          #how to make this check option or custom option depending on the bet?
          bet_option_placements = Placement.objects.filter(
            bet=bet, 
            option=bet_option
            )
          if bet_option_placements:
            player_first_names = ', '.join([bet_option.player.first_name for bet_option in bet_option_placements])
            bet_options_and_names.append(
              {
              'bet_option': bet_option, 
              'player_first_names': player_first_names
              })
          else:
            bet_options_and_names.append(
              {
              'bet_option': bet_option, 
              'player_first_names': ''
              })
        bets_list.append(
          {
          'bet': bet, 
          'bet_options': bet_options_and_names
          })

      # should this be updated to use list comprehension? or ternary operator?
      players_bets_placed = []
      players_bets_awaiting = []
      for player in event.players.all():
        if len(Placement.objects.filter(player=player)) == len(bets):
          players_bets_placed.append(player.first_name)
        else:
          players_bets_awaiting.append(player.first_name)

    except:
      bets_list = None
      players_bets_placed = []
      players_bets_awaiting = []

    # still need to add placements so they render correctly for each user

    #this is reused code from above - move out into a function?
    is_event_started = event.start_time < datetime.datetime.now().replace(tzinfo=pytz.UTC)
    is_event_ended = event.end_time < datetime.datetime.now().replace(tzinfo=pytz.UTC)
    event_status = {
    'is_event_started': is_event_started, 
    'is_event_ended': is_event_ended
    }

    #replace below logic with authentication and logic in view
    is_admin = event_commissioner.id == request.user.id

    return render(
      request, 
      'show-placements.html', 
      {
      'event': event, 
      'group_id': group_id, 
      'event_commissioner': event_commissioner, 
      'bets_list': bets_list, 
      'players_bets_placed': players_bets_placed, 
      'players_bets_awaiting': players_bets_awaiting, 
      'event_status': event_status, 
      'is_admin': is_admin
      })

def create_placements(request, group_id, event_id):
    event = Event.objects.get(
      id=event_id
      )
    user = User.objects.get(
      id=request.user.id
      )

    # need all the logic here - struggling with the JS working


    return HttpResponseRedirect(reverse('show_placements', args=(group_id,event_id,)))

def leaderboard(request, group_id, event_id):
    event = Event.objects.get(
      id=event_id
      )
    event_commissioner = UserEventRole.objects.get(
      role=1, event=event_id
      ).user

    user = User.objects.get(

bettorgame/maingame/templates/add_bets.html
{% include 'base_template.html' %}

<!-- pass group object (per db contains name and particpatns) -->
<h2 class="col text-center">{{ group.name }}</h2>
<h6 class="col text-center">Group ID: {{ group.id }}</h6>
<h6 class="col text-center">Commissioner: {{ group.admin }}</h6>
<h6 class="col text-center">Stakes: {{ group.stakes }}</h6>

</br>

<h4 class="bg-secondary text-white">Participants</h4>
<div class="container">
  <div class="row">
    {% for participant in group.participants %}
      <div class="col-3">
        {{ participant }}
      </div>
    {% endfor %}
  </div>
</div>

</br>
</br>

<h4 class="bg-secondary text-white">Current Bets</h4>
{% for bet in group.bets %}
<div class="container border">
  <div class="row">
      <div class="col font-weight-bold">
        {{ bet.bet }}
      </div>
  </div>
  <div class="row">
      <div class="col font-italic">
        Creator: {{ bet.creator }}
      </div>
  </div>
   <div class="row">
      <div class="col border">
        {{ bet.option_1 }}
      </div>
      <div class="col border">
        {{ bet.option_2 }}
      </div>
  </div>
</div>
</span>
</br>
{% endfor %}

</br>
<form>
  <div class="form-group">
    <h4 class="bg-secondary text-white">Add New Bet</h4>
    <input type="text" class="form-control" id="formAddBetExampleInput" placeholder="Is the DJ going to play Wagon Wheel?">
  </div>
  <div class="row">
    <div class="col">
      <input type="text" class="form-control" placeholder="100% Yes">
    </div>
    <div class="col">
      <input type="text" class="form-control" placeholder="No Chance">
    </div>
  </div>
</br>
  <div class="col text-center">
    <button type="submit" class="btn btn-primary">SUBMIT BET</button>
  </div>
</form>

bettorgame/maingame/templates/base-template.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Nav -->
    <!-- Hide nav if on login or create and join group pages -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'maingame:index' %}">A Bettor Game</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'maingame:add_bets' group_id event.id %}">Add Bets <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{% url 'maingame:show_placements' group_id event.id %}">Make Bets</a>
          <a class="nav-item nav-link" href="{% url 'maingame:leaderboard' group_id event.id %}">Leaderboard</a>
          <a class="nav-item nav-link" href="{% url 'maingame:login' %}">Log out</a>
          {% if request.session.is_admin %}
            <a class="nav-item nav-link" href="{% url 'maingame:group_admin' group_id event.id %}">ADMIN</a>
          {% endif %}
        </div>
      </div>
    </nav>
  </body>
</html>

bettorgame/maingame/templates/base_template.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- JS Functions -->
    {% if not group.started %}
    <script src="js/bet_handlers.js"></script>
    {% endif %}

    <!-- Nav -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Vardo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="#">Add Bets <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="#">Make Bets</a>
          <a class="nav-item nav-link" href="#">Leaderboard</a>
          <a class="nav-item nav-link" href="#">Log out</a>
          {% if group.admin == current_user %}
            <a class="nav-item nav-link" href="#">ADMIN</a>
          {% endif %}
        </div>
      </div>
    </nav>
  </body>
</html>

bettorgame/maingame/templates/group_admin.html
<!-- Redirect to add bets if not group admin -->
{% include 'base_template.html' %}

<form>
  <div class="form-group">
    <h4 class="bg-secondary text-white">Welcome Commissioner!</h4>
    <h5>What are the stakes?</h5>
    <input type="text" class="form-control" id="formSetStakesExampleInput" placeholder="$20, Everyone buys the winner a beer, etc.">
  </div>
  <div class="col text-center">
    <button type="submit" class="btn btn-primary">SUBMIT STAKES</button>
  </div>
</form>

</br>

<h3 class="col text-center">Invite friends to join your group!</h3>
<h6 class="col text-center">Group ID: {{ group.id }}</h6>

</br>

<h5 class="col text-center">As the commissioner, you have special powers and responsibilities. When all members of the group have submitted their picks, come back here and hit the "START GAME!" button to lock all bets in place.<p></br>On the "Make Bets" page, you have the ability to select the winning option when an individual bet is complete.<p></br>When the game is over, come back here and hit "END GAME". Any bets that do not have a winning option selected will result in a push (tie) for that bet.</h5>

<div class="container">
  <div class="row">
   <div class="col text-center">
      <button type="submit" class="btn btn-success">START GAME!</button>
    </div>
   <div class="col text-center">
      <button type="submit" class="btn btn-danger">END GAME</button>
    </div>
  </div>
</div>

bettorgame/maingame/templates/show_placements.html
{% include 'base_template.html' %}

<!-- pass group object (per db contains name and particpatns) -->
<h2 class="col text-center">{{ group.name }}</h2>
<h6 class="col text-center">Group ID: {{ group.id }}</h6>
<h6 class="col text-center">Commissioner: {{ group.admin }}</h6>
<h6 class="col text-center">Stakes: {{ group.stakes }}</h6>


</br>

<h4 class="bg-secondary text-white">Bets Placed</h4>
<div class="container">
  <div class="row">
    {% for participant in group.participants_placed %}
      <div class="col-3">
        {{ participant }}
      </div>
    {% endfor %}
  </div>
</div>

<h4 class="bg-secondary text-white">Awaiting</h4>
<div class="container">
  <div class="row">
    {% for participant in group.participants_awaiting %}
      <div class="col-3">
        {{ participant }}
      </div>
    {% endfor %}
  </div>
</div>

</br>
</br>

<h4 class="bg-secondary text-white">Bets</h4>
{% for bet in group.bets %}
<div class="container border">
  <div class="row">
      <div class="col font-weight-bold">
        {{ bet.bet }}
      </div>
  </div>
  <div class="row">
      <div class="col font-italic">
        Creator: {{ bet.creator }}
      </div>
  </div>
   <div class="row">
      <!-- should store the bet ID and answer ID somewhere in the div? -->
      <div class="col border bet-selection-div">
        {{ bet.option_1 }}
        {% if group.started and not group.ended and group.admin == current_user %}
          <div class="col text-center">
            <button type="submit" class="btn btn-primary">SELECT WINNER</button>
          </div>
        {% endif %}
      </div>
      <div class="col border bet-selection-div">
        {{ bet.option_2 }}
        {% if group.started and not group.ended and group.admin == current_user %}
          <div class="col text-center">
            <button type="submit" class="btn btn-primary">SELECT WINNER</button>
          </div>
        {% endif %}
      </div>
  </div>
</div>
</span>
</br>
{% endfor %}